# Site settings
course_name: Workshop the use of transmission models to simulate foot-and-mouth disease epidemics and the implementation of control actions 
course_description: "In this five-day workshop, we provide a gentle introduction to a range of mathematical models used to simulate the spread and control of livestock diseases. You learn how such models can be used to make informed decisions **before**, **during**, and **after** an animal health emergency.
<br /> We will focus on the application of such epidemiological models while demonstrating their use with real data while simulating FMD outbreaks."
course_semester: "Rio de Janeiro, May 29  to June 2nd, 2023"

baseurl: "/workshop" # the subpath of your site, e.g. /blog/
url: "http://ncespedesc.github.io/" # the base hostname & protocol for your site

schoolname: "PANAFTOSA"
schoolurl: "https://machado-lab.github.io/"
twitter_username: username 

address: |
    Centro Panamericano de Febre Aftosa, Av. Governador Leonel de Moura Brizola, 7778 - Parque Sao Bento, Duque de Caxias
    Rio de Janeiro, Brazil



### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
